name: Master branch checks

on:
  push:
    branches:
      - master
    tags:
      - "[0-9]+.[0-9]+.[0-9]+*"
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  checks:
    uses: ./.github/workflows/shared.yaml
